<?php 
echo __("Russia");
echo __("Saint-Petersburg");
echo __("Moscow");
echo __("Veliky Novgorod");
echo __("Volgograd");
echo __("Yekaterinburg");
echo __("Kazan");
echo __("Kaliningrad");
echo __("Krasnodar");
echo __("Rostov-on-Don");
echo __("Krasnoyarsk");
echo __("Murmansk");
echo __("Nizhny Novgorod");
echo __("Novosibirsk");
echo __("Omsk");
echo __("Perm");
echo __("Samara");
echo __("Saratov");
echo __("Ufa");
echo __("Chelyabinsk");
echo __("Ukraine");
echo __("Kiev");
echo __("Dnipropetrovsk");
echo __("Odessa");
echo __("Germany");
echo __("Munich");
echo __("Karlsruhe");
echo __("Berlin");
echo __("Bonn");
echo __("Bremen");
echo __("Frankfurt am Main");
echo __("Düsseldorf");
echo __("Hamburg");
echo __("Belarus");
echo __("Minsk");
echo __("Brest");
echo __("Vitebsk");
echo __("Gomel");
echo __("Horki");
echo __("Grodno");
echo __("Mogilev");
echo __("Mazyr");
echo __("Navapolatsk");
echo __("Pinsk");
echo __("Baranovichi");
echo __("Israel");
echo __("Ashdod");
echo __("Ashkelon");
echo __("Beersheba");
echo __("Netanya");
echo __("Petah Tikva");
echo __("Rehovot");
echo __("Rishon LeZion");
echo __("Tel Aviv");
echo __("Haifa");
echo __("Jerusalem");
echo __("Kazakhstan");
echo __("Aktau");
echo __("Baikonur");
echo __("Karaganda");
echo __("Kokshetau");
echo __("Pavlodar");
echo __("Petropavlovsk");
echo __("Semey");
echo __("Taraz");
echo __("Uralsk");
echo __("Oskemen");
echo __("Shymkent");
echo __("Astana");
echo __("Almaty");
echo __("USA");
echo __("Boston");
echo __("Chicago");
echo __("Houston");
echo __("Los Angeles");
echo __("New York City");
echo __("Philadelphia");
echo __("San Francisco");
echo __("Washington City");
__('male');
__('female');
?>